# Generated by Django 4.1.1 on 2022-10-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(null=True, unique=True)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('f_nac', models.DateField()),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('grupo_sanguineo', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Cualitativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CualitativaOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cualitativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.cualitativa')),
            ],
            options={
                'verbose_name_plural': 'CualitativaOpciones',
                'db_table': 'gest_lab_cualitativa_opcion',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Examenes',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('costo', models.FloatField()),
                ('uso', models.FloatField()),
                ('dosificacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Opciones',
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.categoria')),
                ('examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gest_lab.examen')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.cargo')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.prueba')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_orden', models.CharField(max_length=15)),
                ('f_solicitud', models.DateTimeField(auto_now_add=True)),
                ('f_proceso', models.DateTimeField(blank=True, null=True)),
                ('f_validado', models.DateTimeField(blank=True, null=True)),
                ('f_entrega', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.cliente')),
                ('entrega_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entragado_por', to='gest_lab.usuario')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.examen')),
                ('proceso_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procesado_por', to='gest_lab.usuario')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.prueba')),
                ('solicitud_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitado_por', to='gest_lab.usuario')),
                ('validado_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validado_por', to='gest_lab.usuario')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='ResultadoDescriptivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.solicitud')),
            ],
            options={
                'verbose_name_plural': 'ResultadosDescriptivos',
            },
        ),
        migrations.CreateModel(
            name='ResultadoCuantitativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.solicitud')),
            ],
            options={
                'verbose_name_plural': 'ResultadosCuantitativos',
            },
        ),
        migrations.CreateModel(
            name='ResultadoCualitativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cualitativa_opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.cualitativaopcion')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.solicitud')),
            ],
            options={
                'verbose_name_plural': 'ResultadosCualitativos',
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('lim_sup', models.FloatField()),
                ('lim_inf', models.FloatField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.insumo')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gest_lab.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.insumo')),
                ('pruebas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.prueba')),
            ],
            options={
                'verbose_name_plural': 'PruebaInsumos',
                'db_table': 'gest_lab_prueba_insumo',
            },
        ),
        migrations.AddField(
            model_name='prueba',
            name='insumos',
            field=models.ManyToManyField(through='gest_lab.PruebaInsumo', to='gest_lab.insumo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gest_lab.unidad'),
        ),
        migrations.CreateModel(
            name='Descriptiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.prueba')),
            ],
        ),
        migrations.CreateModel(
            name='Cuantitativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.prueba')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.unidad')),
            ],
        ),
        migrations.AddField(
            model_name='cualitativaopcion',
            name='opcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.opcion'),
        ),
        migrations.AddField(
            model_name='cualitativa',
            name='opciones',
            field=models.ManyToManyField(through='gest_lab.CualitativaOpcion', to='gest_lab.opcion'),
        ),
        migrations.AddField(
            model_name='cualitativa',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.prueba'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.sexo'),
        ),
    ]
