# Generated by Django 4.1.1 on 2022-10-03 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(null=True)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('f_nac', models.DateField()),
                ('direccion', models.TextField()),
                ('telefono', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cualitativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='cualitativa_opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cualitativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.cualitativa')),
            ],
        ),
        migrations.CreateModel(
            name='examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_orden', models.IntegerField()),
                ('f_solicitud', models.DateTimeField()),
                ('f_proceso', models.DateTimeField()),
                ('f_validado', models.DateTimeField()),
                ('f_entrega', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('costo', models.FloatField()),
                ('uso', models.FloatField()),
                ('dosificacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField()),
                ('test2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('grupo', models.BooleanField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('id_prueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.prueba')),
            ],
        ),
        migrations.CreateModel(
            name='resultado_descriptivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField()),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.examen')),
            ],
        ),
        migrations.CreateModel(
            name='resultado_cuantitativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.examen')),
            ],
        ),
        migrations.CreateModel(
            name='resultado_cualitativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cualitativa_opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.cualitativa_opcion')),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.examen')),
            ],
        ),
        migrations.CreateModel(
            name='rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('lim_sup', models.FloatField()),
                ('lim_inf', models.FloatField()),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.insumo')),
                ('id_sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gest_lab.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.cargo')),
                ('id_sexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='insumo_prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.insumo')),
                ('id_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.prueba')),
            ],
        ),
        migrations.AddField(
            model_name='insumo',
            name='id_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.unidad'),
        ),
        migrations.AddField(
            model_name='examen',
            name='entrega_id_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entragado_por', to='gest_lab.personal'),
        ),
        migrations.AddField(
            model_name='examen',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.cliente'),
        ),
        migrations.AddField(
            model_name='examen',
            name='id_prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.prueba'),
        ),
        migrations.AddField(
            model_name='examen',
            name='proceso_id_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procesado_por', to='gest_lab.personal'),
        ),
        migrations.AddField(
            model_name='examen',
            name='solicitud_id_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitado_por', to='gest_lab.personal'),
        ),
        migrations.AddField(
            model_name='examen',
            name='validado_id_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validado_por', to='gest_lab.personal'),
        ),
        migrations.CreateModel(
            name='descriptiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.prueba')),
            ],
        ),
        migrations.CreateModel(
            name='cuantitativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.prueba')),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.unidad')),
            ],
        ),
        migrations.AddField(
            model_name='cualitativa_opcion',
            name='id_opcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.opcion'),
        ),
        migrations.AddField(
            model_name='cualitativa',
            name='id_prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.prueba'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_grupo_sanguineo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gest_lab.examen'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gest_lab.sexo'),
        ),
        migrations.CreateModel(
            name='analisis_prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.analisis')),
                ('id_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_lab.prueba')),
            ],
        ),
    ]
