# Generated by Django 4.1.1 on 2022-10-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pruebainsumo',
            old_name='pruebas',
            new_name='prueba',
        ),
    ]
