# Generated by Django 4.1.1 on 2022-10-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='pruebas',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='examenes',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='grupo',
        ),
        migrations.AddField(
            model_name='examen',
            name='pruebas',
            field=models.ManyToManyField(to='gest_lab.prueba'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='insumos',
            field=models.ManyToManyField(to='gest_lab.insumo'),
        ),
    ]
