# Generated by Django 4.1.1 on 2022-10-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='unidad',
            field=models.TextField(unique=True),
        ),
    ]
