# Generated by Django 4.1.1 on 2022-10-20 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0002_remove_insumo_pruebas_remove_prueba_examenes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='pruebas',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='insumos',
        ),
        migrations.AddField(
            model_name='prueba',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gest_lab.examen'),
        ),
    ]
