# Generated by Django 4.1.1 on 2022-10-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0002_rename_pruebas_pruebainsumo_prueba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='costo',
            new_name='limite_alerta',
        ),
        migrations.RenameField(
            model_name='insumo',
            old_name='dosificacion',
            new_name='unidades',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='uso',
        ),
    ]
