# Generated by Django 4.1.1 on 2022-10-03 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0002_alter_unidad_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion',
            name='test2',
        ),
    ]
