# Generated by Django 4.1.1 on 2022-10-03 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0003_remove_opcion_test2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='id_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gest_lab.unidad'),
        ),
    ]
