# Generated by Django 4.1.1 on 2022-10-20 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0003_rename_costo_insumo_limite_alerta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='proceso_usuario',
            new_name='procesado_por',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='solicitud_usuario',
            new_name='solicitado_por',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='validado_usuario',
            new_name='validado_por',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='entrega_usuario',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='entregado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregado_por', to='gest_lab.usuario'),
        ),
    ]
