# Generated by Django 4.1.1 on 2022-10-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0003_remove_examen_pruebas_remove_prueba_insumos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion',
            name='cualitativas',
        ),
        migrations.AddField(
            model_name='cualitativa',
            name='opciones',
            field=models.ManyToManyField(through='gest_lab.CualitativaOpcion', to='gest_lab.opcion'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='insumos',
            field=models.ManyToManyField(to='gest_lab.insumo'),
        ),
    ]
