# Generated by Django 4.1.1 on 2022-10-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0004_rename_proceso_usuario_solicitud_procesado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='grupo_sanguineo',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
