# Generated by Django 4.1.1 on 2022-10-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0004_alter_insumo_id_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='n_orden',
            field=models.TextField(),
        ),
    ]
