# Generated by Django 4.1.1 on 2022-10-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0004_remove_opcion_cualitativas_cualitativa_opciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='f_solicitud',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
