# Generated by Django 4.1.1 on 2022-10-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0005_alter_solicitud_f_solicitud'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cualitativaopcion',
            table='CualitativaOpciones',
        ),
        migrations.AlterModelTable(
            name='examen',
            table='Examenes',
        ),
        migrations.AlterModelTable(
            name='opcion',
            table='Opciones',
        ),
        migrations.AlterModelTable(
            name='resultadocualitativo',
            table='ResultadosCualitativos',
        ),
        migrations.AlterModelTable(
            name='resultadocuantitativo',
            table='ResultadosCuantitativos',
        ),
        migrations.AlterModelTable(
            name='resultadodescriptivo',
            table='ResultadosDescriptivos',
        ),
        migrations.AlterModelTable(
            name='solicitud',
            table='Solicitudes',
        ),
        migrations.AlterModelTable(
            name='unidad',
            table='Unidades',
        ),
    ]
