# Generated by Django 4.1.1 on 2022-10-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0005_alter_examen_n_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='f_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='f_proceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='f_validado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
