# Generated by Django 4.1.1 on 2022-10-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0005_alter_cliente_grupo_sanguineo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
