# Generated by Django 4.1.1 on 2022-10-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0006_alter_examen_f_entrega_alter_examen_f_proceso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='examen',
            name='n_orden',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='resultado',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='personal',
            name='apellido',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='unidad',
            field=models.CharField(max_length=10),
        ),
    ]
