# Generated by Django 4.1.1 on 2022-10-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0006_alter_cliente_grupo_sanguineo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
