# Generated by Django 4.1.1 on 2022-10-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0007_alter_analisis_nombre_alter_cargo_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
