# Generated by Django 4.1.1 on 2022-10-18 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gest_lab', '0008_alter_cliente_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='id_analisis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gest_lab.analisis'),
            preserve_default=False,
        ),
    ]
